language: node_js
node_js: 0.10
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
after_script: cat ./build/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
